-- Migration: drop legacy completion columns (D10)
-- Created: 2026-06-21
-- Author: system
-- MANUAL: TRUE
-- Description:
--   Phase D (Dependency Bus) of the decouple architecture. Drops the
--   legacy completion-state columns that were used by the
--   CorrelationManager (pre-Bus) implementation:
--
--     * ``instances.waiting_for`` (INTEGER, count of pending children)
--     * ``instances.children``     (TEXT/JSON, denormalized cache of child IDs)
--
--   NOTE: This migration intentionally does NOT drop the
--   ``instance_hierarchy`` junction table. That table is the live
--   canonical working-set source for parent->child relationships and
--   is actively used by the Dependency Bus / spawn / completion paths.
--
--   After the Dependency Bus is the single completion authority,
--   these column caches are dead artifacts:
--
--     - ``waiting_for`` was a REBUILD-ONLY cache, never read for
--       runtime control flow (CorrelationManager.is_complete() /
--       get_pending_count() are the source of truth). See C10.
--     - ``children`` was the denormalized cache that was doubly
--       broken (RMW races at 4 sites AND overridden on every read
--       via _enrich_instance()). See C10.
--
--   ============================================================================
--   WARNING: THIS MIGRATION IS IRREVERSIBLE AND DATA-DESTRUCTIVE.
--   ============================================================================
--   All data in the dropped columns is PERMANENTLY LOST
--   after this migration runs. The DOWN section below recreates the
--   schema (empty columns) but the data is gone --
--   there is no recovery path.
--
--   This migration is NOT auto-applied. Per the reviewer's §7.2
--   recommendation, it exists as a file so operators can apply it
--   manually AFTER 2+ weeks of clean Dependency Bus operation in
--   production. Do NOT apply until:
--
--     1. The Dependency Bus flag has been ON in production for
--        2+ weeks with no rollbacks to ``USE_LEGACY_WAITING_FOR_CASCADE``.
--     2. A pre-migration snapshot/backup of the database has been
--        taken and verified.
--     3. Operators are on-call and prepared to roll forward (the
--        DOWN section below does NOT restore data).
--
--   ============================================================================
--   WARNING: RUNNING THIS DESTROYS THE CORRELATION-MANAGER ROLLBACK PATH.
--   ============================================================================
--   The ``waiting_for`` column holds the rebuild cache that the
--   legacy CorrelationManager kill-switch
--   (``USE_LEGACY_WAITING_FOR_CASCADE=ON``) depends on. After this
--   migration runs, setting ``USE_DEPENDENCY_BUS=false`` will have
--   NO ``waiting_for`` data to fall back to. Verify the Dependency
--   Bus is fully clean before applying.
--
--   ============================================================================
--   Dialect notes:
--     - PostgreSQL: supports ``ALTER TABLE ... DROP COLUMN IF EXISTS``
--       natively. This is the recommended target environment. The
--       migration runner NO-OPs all .sql files on PostgreSQL
--       (runner.py lines 455-482), so this file is INERT on
--       PostgreSQL until an operator applies it manually (e.g.
--       via psql) -- which is the intended behavior.
--     - SQLite 3.35.0+ supports ``ALTER TABLE ... DROP COLUMN`` but
--       does NOT support the ``IF EXISTS`` variant. The migration
--       runner DOES pick up .sql files on SQLite. If you intend to
--       run this on SQLite, either (a) skip the file via the
--       runner's filter mechanism, (b) hand-edit the UP section
--       to drop the IF EXISTS clauses, or (c) upgrade SQLite and
--       accept the first-run syntax error on a one-time manual
--       retry.
--
--   Schema reference: daemon/repositories/instance/models.py
--     - ``Instance.waiting_for``  line 79 (INTEGER, default 0)
--     - ``Instance.children``      line 73 (TEXT, default '[]')

-- UP

-- Drop waiting_for (count of pending children; rebuild-only cache,
-- never read for runtime control flow).
ALTER TABLE instances DROP COLUMN IF EXISTS waiting_for;

-- Drop children (denormalized JSON cache of child IDs; replaced by
-- enrichment from instance_hierarchy on every read; doubly broken
-- under contention per C10).
ALTER TABLE instances DROP COLUMN IF EXISTS children;

-- NOTE: ``instance_hierarchy`` junction table is intentionally
-- NOT dropped here. It is the live canonical working-set source
-- for parent->child relationships. The legacy ``children`` JSON
-- cache was a doubly-broken duplicate of that table's content.

-- DOWN
-- ============================================================================
-- DATA LOSS WARNING
-- ============================================================================
-- This DOWN section recreates the columns as empty containers. The
-- data that was in those columns at the time the UP migration ran is
-- PERMANENTLY LOST. Rolling back does NOT restore the data -- it only
-- restores the ability for new instances to write to those columns.
-- Schema recreation is NOT data recovery.

-- Recreate waiting_for as INTEGER (rebuild-only cache; default 0).
-- Matches the SQLModel definition at
-- daemon/repositories/instance/models.py:79.
ALTER TABLE instances ADD COLUMN waiting_for INTEGER NOT NULL DEFAULT 0;

-- Recreate children as TEXT (denormalized cache; default '[]').
-- Matches the SQLModel definition at
-- daemon/repositories/instance/models.py:73.
ALTER TABLE instances ADD COLUMN children TEXT NOT NULL DEFAULT '[]';
