"""Native Python tools for opencode session orchestration.

Replaces the Go binary `opencode_skill`. All tools use `external_opencode_*`
prefix and category `external_opencode`. The factory function
`create_opencode_tools()` follows the same closure-injection pattern as
`daemon/tools/knowledge_tools.py`.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

from langchain_core.tools import tool

from daemon.opencode.constants import POLL_INTERVAL_S
from daemon.opencode.server import (
    external_opencode_send_message as _server_send_message,  # Blocker 1 (Rev 4): alias to avoid name collision with LangChain tool of same name
)
from ._tool_registry import register_tool_category

if TYPE_CHECKING:
    from daemon.manager import InstanceManager
    from daemon.opencode.server import OpenCodeRequest, OpenCodeResponse
    from daemon.opencode.registry import OpenCodeSessionRegistry

logger = logging.getLogger(__name__)

CATEGORY_NAME = "OpenCode"
CATEGORY_DOC = """\
OpenCode session orchestration tools for controlling the OpenCode AI coding tool.

These tools communicate with an EXTERNAL system (OpenCode at http://127.0.0.1:4095).
They manage session lifecycle: create, send messages, check status, wait for results,
answer interactive questions, resume, and abort.

**Workflow**:
1. `external_opencode_init_session` — Create or replace a named session
2. `external_opencode_send_message` — Send prompt (fire-and-forget)
3. `external_opencode_wait_for_result` — Block until completion (or `external_opencode_wait_any` for parallel)
4. `external_opencode_get_status` — Non-blocking status check
5. `external_opencode_answer_question` — Answer interactive questions
6. `external_opencode_resume_session` — Resume after timeout
7. `external_opencode_abort_session` — Abort and reset to IDLE
"""


def create_opencode_tools(
    manager: "InstanceManager",
    current_instance_id: str,
) -> list:
    """Create opencode orchestration tools with injected manager reference.
    
    Args:
        manager: The InstanceManager instance (provides opencode_registry).
        current_instance_id: The ID of the current instance (unused for now
            but kept for pattern parity with knowledge_tools).

    Returns:
        List of 8 tool functions.
    """

    def _get_registry() -> "OpenCodeSessionRegistry":
        """Get the opencode session registry from manager (Phase 3 wiring)."""
        registry = getattr(manager, 'opencode_registry', None)
        if registry is None:
            raise RuntimeError(
                "OpenCode session registry not initialized. "
                "Check daemon startup logs for 'opencode' configuration."
            )
        return registry
    
    async def _send(request: "OpenCodeRequest") -> "OpenCodeResponse":
        """Dispatch an OpenCodeRequest and return the response."""
        # Blocker 1 (Rev 4): Call the server dispatcher via the aliased import,
        # NOT the local LangChain tool `external_opencode_send_message` which
        # would receive an OpenCodeRequest as a positional arg (wrong function).
        return await _server_send_message(request, _get_registry())
    
    def _format_response(resp: "OpenCodeResponse") -> str:
        """Format an OpenCodeResponse for agent consumption."""
        if resp.status == "ok":
            return resp.message or f"[OK] {resp.data or ''}"
        return f"[ERROR] {resp.message}"
    
    # ── Tool 1: Init Session ────────────────────────────────────────
    
    @register_tool_category("external_opencode")
    @tool
    async def external_opencode_init_session(
        project: str,
        session_name: str,
        working_dir: str,
    ) -> str:
        """Initialize a new opencode session. Replaces existing if one exists.
        
        Use tool_help("external_opencode_init_session") for details.
        """
        from daemon.opencode.server import OpenCodeRequest
        
        req = OpenCodeRequest(
            action="INIT_SESSION",
            payload={"project": project, "session_name": session_name, "working_dir": working_dir},
        )
        resp = await _send(req)
        if resp.status == "ok":
            return f"[SUCCESS] Session '{session_name}' initialized with ID {resp.session_id} in {working_dir}"
        return _format_response(resp)
    
    external_opencode_init_session._full_doc_ = """\
Initialize a new opencode session for a project. Replaces existing session if one exists.

Args:
    project: Project identifier (e.g. "myapp")
    session_name: Human-readable name (e.g. "feature-login")
    working_dir: Absolute path to the working directory

Returns:
    Success message with session ID, or error message.

The session ID is auto-generated by OpenCode. Use this session name in all
subsequent calls to other opencode_* tools.

Conflicts with existing sessions are resolved by aborting the old remote
session and deleting its registry entry before creating the new one.
"""
    
    # ── Tool 2: Send Message ────────────────────────────────────────
    
    @register_tool_category("external_opencode")
    @tool
    async def external_opencode_send_message(
        project: str,
        session_name: str,
        message: str,
        agent: str = "orchestrator",
        model: str | None = None,
    ) -> str:
        """Send a prompt to an opencode session (fire-and-forget).
        
        Use tool_help("external_opencode_send_message") for details.
        """
        from daemon.opencode.server import OpenCodeRequest
        
        # Parse model "provider/model" format
        model_dict = {"providerID": "litellm", "modelID": "coding"}
        if model and "/" in model:
            provider, model_id = model.split("/", 1)
            model_dict = {"providerID": provider, "modelID": model_id}
        elif model:
            model_dict = {"providerID": "litellm", "modelID": model}
        
        # Look up session_id from registry via PUBLIC delegate (Issue 4)
        registry = _get_registry()
        record = await registry.get_session_record(project, session_name)
        if record is None:
            return f"[ERROR] Session '{session_name}' not found in project '{project}'"
        session_id = record.get("id", "")
        
        req = OpenCodeRequest(
            action="PROMPT",
            session_id=session_id,
            payload={
                "agent": agent,
                "model": model_dict,
                "parts": [{"type": "text", "text": message}],
            },
        )
        resp = await _send(req)
        if resp.status == "ok":
            return f"[SUBMITTED] Message sent. Run external_opencode_get_status('{project}', '{session_name}') to check progress."
        return _format_response(resp)
    
    external_opencode_send_message._full_doc_ = """\
Send a prompt to an opencode session (fire-and-forget).

Args:
    project: Project identifier
    session_name: Session name
    message: The text message to send
    agent: Agent name (default "orchestrator")
    model: Optional model in "provider/model" format (default "litellm/coding")

Returns:
    Submitted confirmation or error.

Special prompts (bypass BUSY check):
- "start-work" — also locks agent to "atlas"
- "continue" — routes through RESUME (hardcoded prompt)
- "retry" — routes through RESUME
- "abort" — bypasses BUSY (use external_opencode_abort_session for the real action)
"""
    
    # ── Tool 3: Get Status ──────────────────────────────────────────
    
    @register_tool_category("external_opencode")
    @tool
    async def external_opencode_get_status(
        project: str,
        session_name: str,
    ) -> str:
        """Get current status of an opencode session (non-blocking).
        
        Use tool_help("external_opencode_get_status") for details.
        """
        from daemon.opencode.server import OpenCodeRequest
        
        registry = _get_registry()
        record = await registry.get_session_record(project, session_name)
        if record is None:
            return f"[ERROR] Session '{session_name}' not found in project '{project}'"
        session_id = record.get("id", "")
        
        req = OpenCodeRequest(action="GET_STATUS", session_id=session_id)
        resp = await _send(req)
        if resp.status == "ok":
            data = resp.data or {}
            state = data.get("state", "UNKNOWN")
            response = data.get("latest_response", "Processing...")
            questions = data.get("questions", [])
            
            output = [
                f"State: {state}",
                f"Last Activity: {record.get('last_activity', '')}",
                "",
                "Latest Response:",
                str(response) if response else "(none)",
            ]
            if questions:
                output.append("")
                output.append("Questions:")
                for q in questions:
                    output.append(f"  [?] {q.get('id', '')}: {q.get('questions', [])}")
            return "\n".join(output)
        return _format_response(resp)
    
    external_opencode_get_status._full_doc_ = """\
Get current status of an opencode session (non-blocking).

Args:
    project: Project identifier
    session_name: Session name

Returns:
    Formatted status including state, last activity, latest response, and pending questions.
"""
    
    # ── Tool 4: Wait for Result ─────────────────────────────────────
    
    @register_tool_category("external_opencode")
    @tool
    async def external_opencode_wait_for_result(
        project: str,
        session_name: str,
        timeout: int = 600,
    ) -> str:
        """Block until an opencode session completes.
        
        Use tool_help("external_opencode_wait_for_result") for details.
        """
        registry = _get_registry()
        record = await registry.get_session_record(project, session_name)
        if record is None:
            return f"[ERROR] Session '{session_name}' not found in project '{project}'"
        session_id = record.get("id", "")
        
        loop = asyncio.get_running_loop()
        deadline = loop.time() + timeout
        while loop.time() < deadline:
            from daemon.opencode.server import OpenCodeRequest
            req = OpenCodeRequest(action="GET_STATUS", session_id=session_id)
            resp = await _send(req)
            if resp.status == "ok":
                data = resp.data or {}
                state = data.get("state", "UNKNOWN")
                if state == "IDLE":
                    return f"[COMPLETED] Session completed.\n{_format_response(resp)}"
                if state == "WAITING_FOR_INPUT":
                    return f"[WAITING_FOR_INPUT] Session needs input. Use external_opencode_get_status() to see questions."
            await asyncio.sleep(POLL_INTERVAL_S)
        
        return f"[TIMEOUT] Session did not complete within {timeout}s. Use external_opencode_resume_session() to continue."
    
    external_opencode_wait_for_result._full_doc_ = """\
Block until an opencode session completes (polls every 30s, default max 10min).

Args:
    project: Project identifier
    session_name: Session name
    timeout: Max wait in seconds (default 600 = 10 min)

Returns:
    [COMPLETED] message with response data, [WAITING_FOR_INPUT] with question pointer, or [TIMEOUT] message.
"""
    
    # ── Tool 5: Wait Any ────────────────────────────────────────────
    
    @register_tool_category("external_opencode")
    @tool
    async def external_opencode_wait_any(
        sessions: list[dict[str, str]],
        timeout: int = 600,
    ) -> str:
        """Block until ANY of multiple opencode sessions completes.
        
        Use tool_help("external_opencode_wait_any") for details.
        """
        if not sessions:
            return "[ERROR] sessions list is empty"
        
        loop = asyncio.get_running_loop()
        deadline = loop.time() + timeout
        registry = _get_registry()
        
        # Resolve session_id for each — in parallel via asyncio.gather (Issue 5)
        async def _resolve(s: dict[str, str]) -> dict[str, str] | None:
            project = s.get("project", "")
            session_name = s.get("session_name", "")
            record = await registry.get_session_record(project, session_name)
            if record is None:
                return None
            return {
                "project": project,
                "session_name": session_name,
                "session_id": record.get("id", ""),
            }
        
        resolved = await asyncio.gather(*[_resolve(s) for s in sessions])
        session_data = [r for r in resolved if r is not None]
        
        if not session_data:
            return "[ERROR] No valid sessions found"
        
        while loop.time() < deadline:
            from daemon.opencode.server import OpenCodeRequest
            
            # Poll all sessions in PARALLEL (Issue 5: was sequential → now gather)
            async def _check_status(sd: dict[str, str]) -> tuple[dict[str, str], OpenCodeResponse]:
                req = OpenCodeRequest(action="GET_STATUS", session_id=sd["session_id"])
                resp = await _send(req)
                return (sd, resp)
            
            results = await asyncio.gather(*[_check_status(sd) for sd in session_data])
            
            completed = []
            still_running = []
            for sd, resp in results:
                if resp.status == "ok":
                    state = (resp.data or {}).get("state", "UNKNOWN")
                    if state in ("IDLE", "WAITING_FOR_INPUT"):
                        completed.append((sd, resp))
                    else:
                        still_running.append(sd)
            
            if completed:
                lines = [f"[SUMMARY] {len(completed)}/{len(session_data)} sessions completed", ""]
                for sd in session_data:
                    marker = "✓" if any(c[0] == sd for c in completed) else "..."
                    lines.append(f"  {marker} {sd['project']}:{sd['session_name']}")
                lines.append("")
                lines.append("─" * 60)
                lines.append("  COMPLETED RESPONSES")
                lines.append("─" * 60)
                for sd, resp in completed:
                    lines.append(f"\n[{sd['project']}:{sd['session_name']}]")
                    lines.append(_format_response(resp))
                return "\n".join(lines)
            
            await asyncio.sleep(POLL_INTERVAL_S)

        return f"[TIMEOUT] No session completed within {timeout}s. Use external_opencode_get_status() to check each."
    
    external_opencode_wait_any._full_doc_ = """\
Block until ANY of multiple opencode sessions completes (polls every 30s).

Args:
    sessions: List of {"project": "...", "session_name": "..."} objects (max 3 recommended)
    timeout: Max wait in seconds (default 600 = 10 min)

Returns:
    Summary with completed sessions and their responses.
"""
    
    # ── Tool 6: Answer Question ─────────────────────────────────────
    
    @register_tool_category("external_opencode")
    @tool
    async def external_opencode_answer_question(
        project: str,
        session_name: str,
        request_id: str,
        answers: list[str],
    ) -> str:
        """Answer interactive questions from an opencode session.
        
        Use tool_help("external_opencode_answer_question") for details.
        """
        from daemon.opencode.server import OpenCodeRequest
        
        registry = _get_registry()
        record = await registry.get_session_record(project, session_name)  # Issue 4: public delegate
        if record is None:
            return f"[ERROR] Session '{session_name}' not found in project '{project}'"
        session_id = record.get("id", "")
        
        req = OpenCodeRequest(
            action="ANSWER",
            session_id=session_id,
            payload={
                "requestID": request_id,  # camelCase per OpenCode API
                "answers": [answers],  # nested: one row per question, multiple answers per row
            },
        )
        resp = await _send(req)
        if resp.status == "ok":
            return f"[ANSWERED] Submitted answers for request {request_id}: {answers}"
        return _format_response(resp)
    
    external_opencode_answer_question._full_doc_ = """\
Answer interactive questions from an opencode session.

Args:
    project: Project identifier
    session_name: Session name
    request_id: The question ID from external_opencode_get_status()
    answers: List of answer strings (one per sub-question)

Returns:
    Confirmation of submitted answers.

Use external_opencode_get_status() to see pending questions and their IDs.
"""
    
    # ── Tool 7: Resume Session ──────────────────────────────────────
    
    @register_tool_category("external_opencode")
    @tool
    async def external_opencode_resume_session(
        project: str,
        session_name: str,
    ) -> str:
        """Resume a timed-out opencode session.
        
        Use tool_help("external_opencode_resume_session") for details.
        """
        from daemon.opencode.server import OpenCodeRequest
        
        registry = _get_registry()
        record = await registry.get_session_record(project, session_name)  # Issue 4: public delegate
        if record is None:
            return f"[ERROR] Session '{session_name}' not found in project '{project}'"
        session_id = record.get("id", "")
        
        req = OpenCodeRequest(action="RESUME", session_id=session_id)
        resp = await _send(req)
        if resp.status == "ok":
            return f"[RESUMED] Session resumed. Use external_opencode_wait_for_result() to wait for completion."
        return _format_response(resp)
    
    external_opencode_resume_session._full_doc_ = """\
Resume a timed-out opencode session.

Sends a hardcoded resume prompt: agent="orchestrator", model="litellm/coding", text="resume".

Args:
    project: Project identifier
    session_name: Session name

Returns:
    Confirmation or error.
"""
    
    # ── Tool 8: Abort Session ───────────────────────────────────────
    
    @register_tool_category("external_opencode")
    @tool
    async def external_opencode_abort_session(
        project: str,
        session_name: str,
    ) -> str:
        """Abort a running opencode session and reset to IDLE.
        
        Use tool_help("external_opencode_abort_session") for details.
        """
        from daemon.opencode.server import OpenCodeRequest
        
        req = OpenCodeRequest(
            action="ABORT_SESSION",
            payload={"project": project, "session_name": session_name},
        )
        resp = await _send(req)
        if resp.status == "ok":
            return f"[ABORTED] {resp.message or 'Session aborted and ready for new input.'}"
        return _format_response(resp)
    
    external_opencode_abort_session._full_doc_ = """\
Abort a running opencode session and reset to IDLE.

Best-effort remote abort (logs failures), 3-second settle delay, then resets
local state via abort_task().

Args:
    project: Project identifier
    session_name: Session name

Returns:
    Confirmation or error.
"""
    
    return [
        external_opencode_init_session,
        external_opencode_send_message,
        external_opencode_get_status,
        external_opencode_wait_for_result,
        external_opencode_wait_any,
        external_opencode_answer_question,
        external_opencode_resume_session,
        external_opencode_abort_session,
    ]
